# launch the rabbitmq service and the worker and distributor services using Docker services

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  worker:
    build: HyyWorker/.
    networks:
      - rabbit
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  distributor:
    build: HyyDistributor/.
    networks:
      - rabbit
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  collector:
    build: HyyCollector/.
    networks:
      - rabbit
    volumes:
      - collector_data:/app/data
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

networks:
  rabbit:
    driver: overlay
    attachable: true

volumes:
  collector_data:
